### ISSUE TITLE
mysql wont work async

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorerX#51] opened 2017-12-28 17:52 UTC
just tested with version logics have me (13.3-snapshot). 
mysql wont connect. and on the 13.2 release it did

**Comment by DoNotSpamPls** [comment] 2017-12-28 19:26
Can't reproduce, maybe you're on an old version?

**Comment by DoNotSpamPls** [comment] 2017-12-29 08:35
this was my messup, fixed in d2a9a1c

**Closed by DoNotSpamPls** 2017-12-29 08:35 UTC
Labels: bug, can't reproduce, P: High
